cypress/e2e/administration.cy.ts
cypress/e2e/c8yclient.cy.ts
cypress/e2e/dates.cy.ts
cypress/e2e/general.cy.ts
cypress/e2e/login.cy.ts
lib/commands/administration.js
lib/commands/c8yclient.d.ts
lib/commands/c8yclient.js
lib/commands/login.d.ts
lib/commands/utils.js

`c8y/client` has some special handling of users that might be confusing when using `cy.c8yclient`. 
Behaviour of `cy.c8yclient` now changed to:
1. prefer basic auth if passed as previousSubject as with `cy.getAuth(...).c8yclient(...)`. this is similar to using `preferBasicAuth` option. 
2. debug logging of `CookieAuth` and `BasicAuth` being used or available to `c8y/client`
3. debug log user for `CookieAuth` and `BasicAuth`
`cy.login` now stores the logged in user as Cypress env `C8Y_LOGGED_IN_USER`.

#19: improve logging of user for c8yclient commands

---

lib/commands/c8yclient.ts
lib/pacts/c8ypact.ts
lib/pacts/matcher.ts
package-lock.json
package.json
runner/package-lock.json
runner/package.json
test/cypress/e2e/c8yclient.cy.ts
test/cypress/e2e/c8ypact-matcher.cy.ts
test/cypress/e2e/c8ypact.cy.ts

Enable JsonSchema based matching instead of just object matching currently available for validating contracts.

#46: allow schema based pact matching

---

doc/API and Integration Testing.md
lib/commands/c8yclient.ts
lib/pacts/preprocessor.ts
lib/pacts/schema.ts
test/cypress/e2e/c8ypact.cy.ts

- failing tests with match return pact not found
- schema matching add additional properties even if not exist
- fix C8Y_PACT_IGNORE now used for ignoring pacts instead of preprocessor ignore

Fix matching issues and failing tests

---

src/shared/c8ypact/matcher.ts
test/cypress/e2e/c8ypact-matcher.cy.ts

Objects and arrays have not been processed correctly. Issue introduced with using lodash `_.isObjectLike`.
Also fixed processing of arrays.

Fix object and array matching for C8yDefaultPactMatcher

---

package-lock.json
src/lib/pact/cypresspact.ts
src/shared/c8ypact/c8ypact.spec.ts
src/shared/c8ypact/c8ypact.ts
src/shared/c8ypact/fileadapter.ts
test/cypress/e2e/c8ypact.cy.ts

Very basic integration with upcoming `c8yctrl`. 
- added `pactId()`
- added `Cypress.c8ypact.on.suiteStart` as a hook for calling `c8yctrl`

c8yctrl backward support

---

README.md
src/lib/commands/administration.ts
src/lib/commands/requires.ts
src/lib/pact/cypresspact.ts
src/lib/utils.ts
src/shared/c8ypact/c8ypact.ts
src/shared/versioning.ts
test/cypress/e2e/administration.cy.ts
test/cypress/e2e/c8ypact.cy.ts
test/cypress/e2e/requires.cy.ts

Add new custom command `cy.getShellVersion()`
Provide shell application using `C8Y_SHELL_NAME`.
Support shell and system version in requires annotation.

Support shell and system version in requires annotation

---

src/contrib/ajv.ts
src/index.ts
src/lib/commands/requires.ts

The `> Cannot find module 'fs'` error for component and e2e tests has been fixed. 
Closes #150

fix(commands): Fix "cumulocity-cypress" import for commands

---

src/lib/commands/administration.ts
test/cypress/e2e/administration.cy.ts

`cy.getTenantId()` threw an error after `cy.login()` set authorization cookies in the environment. 
Closes #153

fix(commands): Fixed cy.getTenantId with authorization cookies in env

---

src/lib/screenshots/types.ts
src/plugin/index.spec.ts
src/plugin/index.ts
src/screenshot/config.ts
src/screenshot/helper.spec.ts
src/screenshot/helper.ts
src/screenshot/runner.ts
src/screenshot/startup.ts
src/shared/c8ypact/fileadapter.ts

The screenshot folder was cleared before every run of `c8yscrn`. To clear the screenshot folder, use the `--clear` command line option when running `c8yscrn` to avoid unintented data loss. The `global.overwrite` setting in the workflow file is now considered for `run`.  If disabled, existing screenshots are not overwritten.

fix(c8yscrn): Fix setting of screenshot target folder overwrite 

---

src/screenshot/helper.spec.ts
src/screenshot/helper.ts
src/screenshot/startup.ts

The `baseUrl` configured in the config file was ignored. It is now used if not overwritten using `baseUrl` command line option or `C8Y_BASEURL` env variable.

fix(c8yscrn): Fix using baseUrl from config file

---

src/lib/screenshots/types.ts
src/screenshot/runner.ts
src/screenshot/schema.json

Visit wait selector is using new default that works with latest Cumulocity. Added support for overwriting visit selector globally with `global.visitWaitSelector`.

fix(c8yscrn): Use new default wait selector for visit

---

src/lib/screenshots/types.ts
src/screenshot/runner.ts
src/screenshot/schema.json

It is now possible to use `data-cy` for an action without nesting in a `selector`.

fix(c8yscrn): Use data-cy outside of selectors

---

src/plugin/index.ts

Screenshot height might have been less to what has been configured. With this fix the viewport height is configured big enough to fit browser window with desired height and possibly additional controls.

fix(c8yscrn): Fix screenshot height by increasing viewportHeight

---

src/lib/screenshots/types.ts
src/plugin/index.ts
src/screenshot/runner-helper.spec.ts
src/screenshot/runner-helper.ts
src/screenshot/runner.ts
src/screenshot/schema.json
src/screenshot/startup.ts

Reusable selector definitions should help organizing workflows and keep them more readable and maintainable. Define reusable selectors as new root array or object `selectors` in the config yaml file. This is especially helpful if there are no `data-cy` attributes for the DOM element referenced by your workflow. Example:
``` yaml
selectors:
- treeview.collapse.first: ".c8y-tree-view-node .collapse-btn:first"
- treeview.collapse.first.checkbox: "c8y-tree-view-node:has(.collapse-btn:visible:first) .c8y-checkbox:first"
```

fix(c8yscrn): Allow definition of reusable selectors

---

doc/Screenshot Automation.md
src/lib/screenshots/types.ts
src/screenshot/runner.ts
src/screenshot/schema.json

Support typing text into multiple textfields with a single type action. Provide array of strings as value to type values in sequence into all text fields within the selector.

fix(c8yscrn): Support multiple textfields with one type action

---

doc/Screenshot Automation.md
src/lib/screenshots/types.ts
src/screenshot/runner.ts
src/screenshot/schema.json

The `screenshot` action now allows to pass a string directly instead of the `path` for the screenshot name. 
```yaml
- screenshot:
path: path/to/my/screenshot.png 
- screenshot: path/to/my/screenshot.png 
```

fix(c8yscrn): ScreenshotAction string value for path

---

src/screenshot/runner-helper.ts
src/screenshot/runner.ts

When elements have parents that for example have `display: contents` set, the parents are actually not visible and have a 0 bounding rect. This could break calculation of highlight rect if selector matches multiple DOM elements. Now parents with 0 bounding rect are ignored.

fix(c8yscrn): Fix highlighting elements with parents having 0 bounding rect

---

README.md
src/lib/commands/general.ts
src/lib/commands/login.ts
test/cypress/app/apps/public/public-options/options.json
test/cypress/app/apps/public/public-options@app-cockpit/options.json
test/cypress/e2e/general.cy.ts
test/cypress/e2e/login.cy.ts

The `hideCookieBanner` command now maintains the `policyVersion`. Cookies can now be removed using `showCookieBanner`.

fix(command): Fix hideCookieBanner command

---

README.md
src/lib/commands/general.ts
test/cypress/e2e/general.cy.ts

The `cy.showCookieBanner` command did remove the accepted cookie from the session, but the public options request was still intercepted and would set a new cookie. With this fix, the interception will not set a new cookie. To address possible issues with `policyVersion` now required to match for the cookie banner to not show, the `cy.disableCookieBanner` command has been introduced. By disabling the cookie banner, Cumulocity will not check cookie and policy versions.

fix(commands): Fixed showCookieBanner and added disableCookieBanner

---

src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

The `type` action multistep support using arrays as `value` has been fixed. It now supports `null` within the array to skip an entry and uses `input[type=text]` as well as `textarea`.

fix(c8yscrn): Fixed multistep form support for type action

---

src/c8yscrn/startup.ts

`c8yscrn` now returns number of failed screenshot workflows as exit code.

fix(c8yscrn): Return non-zero exit code on failure

---

src/c8yscrn/startup.ts
src/shared/util.spec.ts
src/shared/util.ts

All env variables starting with `C8Y_` or ending with `_username` or `_password` are now passed from the environment into the screenshot workflows. Use `DEBUG=c8y:scrn:env` for logging what is passed.

fix(c8yscrn): Pass all auth env variables from environment

---

doc/Screenshot Automation.md
src/c8yscrn/helper.ts
src/c8yscrn/startup.ts
src/lib/screenshots/types.ts
src/plugin/index.ts

For failing workflows, the target folder for failure screenshots can now be configured using the `failureFolder` command line argument. To disable screenshots on failure, use the `skipFailure` argument.

fix(c8yscrn): Add failure screenshot config options

---

README.md
package.json

Imports from `cumulocity-cypress/lib/*` have been fixed. The documentation has been updated with the current import paths. Refactoring and reorganisation in 0.8.x has been updated to enable backward compatibility with imports from `*/lib/*`.

fix: Fixed lib/* exports

---

doc/Proxy based Testing.md
doc/Screenshot Automation.md
src/c8yctrl/startup-util.spec.ts
src/c8yctrl/startup-util.ts
src/c8yscrn/runner.ts

Now using `C8YCTRL` as prefix for all env variables. Most of old env variables are still supported for backward compatibility. It is however required to update the env variables to prepare for future changes. A list of all env variables can be found in the [documentation](https://github.com/Cumulocity-IoT/cumulocity-cypress/blob/develop/doc/Proxy%20based%20Testing.md#environment-variables).

fix(c8yctrl): Updated env variables to use C8YCTRL prefix

---

packages/pact-runner/cypress/support/e2e.ts
src/lib/pact/runner.ts
src/shared/c8ypact/c8ydefaultpact.spec.ts
src/shared/c8ypact/c8ydefaultpactrecord.spec.ts
src/shared/c8ypact/c8ydefaultpactrecord.ts
src/shared/c8ypact/c8ypact.ts

Authorization is now determined from record auth object, but also from request headers. Using `C8Y_PACT_RUNNER_AUTH` env variable it is now possible to overwrite auth type to `CookieAuth` or `BasicAuth`.

fix(pactrunner): Improved authorization type detection in pactrunner

---

src/lib/commands/highlight.ts
src/shared/types.ts

The `cy.highlight()` default styling options are now exported as `C8yHighlightStyleDefaults`. Use to overwrite defaults.

fix(commands): Export default cy.highlight styling options

---

src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

Screenshots for selectors returning multiple elements has been fixed. `c8yscrn` now calculates the union rect for all elements and translates it to clipping area. You can now also provide per screenshot `padding` which is also applied to union rects in case of multiple elements returned by selector. Required as Cypress does not allow taking screenshots for multiple elements.

fix(c8yscrn): Fixed screenshots for selector returning multiple elements

---

README.md
doc/Screenshot Automation.md
src/c8yscrn/runner.ts
src/lib/commands/screenshot.ts
test/cypress.config.ts
test/cypress/e2e/screenshot.cy.ts

Added custom implementation of `cy.screenshot` to take screenshots of multiple DOM elements. The union rect will be calculated and used for the screenshot. You need to `import "cumulocity-cypress/commands/screenshot`.

fix(commands): Added cy.screenshot overwritten command

---

doc/Screenshot Automation.md
src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

The `login` configuration now allows overriding the user information of the logged in user. Use for mocking user information in the UI, including name, id, email, etc.

fix(c8yscrn): Allow mocking user information

---

src/c8yscrn/runner-helper.spec.ts
src/c8yscrn/runner-helper.ts
src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

It is now possible to provide an array of languages to run the same screenshot workflow for each localization. The first language in the array is considered the default language. All screenshots of other languages will have a `_<locale>.png` in its name.

fix(c8yscrn): Added multiple language run support

---

doc/Screenshot Automation.md
src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

The user property now allows overriding the user information of the logged in user. Use for mocking user information in the UI, including name, id, email, etc.

fix(c8yscrn): Use user property for mocking user information

---

doc/Screenshot Automation.md
src/c8yscrn/runner-helper.spec.ts
src/c8yscrn/runner-helper.ts
src/c8yscrn/schema.json
src/lib/screenshots/types.ts

Selectors can now be localized using the `language` and `localized` properties of `selector`. This is required when running screenshot workflows for multiple languages and selectors reference text in the user interface.

fix(c8yscrn): Added selector localization support

---

src/lib/pact/runner.ts
src/plugin/index.ts
src/shared/c8ypact/adapter/fileadapter.ts
src/shared/c8ypact/matcher.ts
src/shared/util.spec.ts
src/shared/util.ts

The pact-runner now allows providing multiple auth user aliases to rerun the same pact request multiple times with different users. User for permission testing assuming the same response for different users with different roles / permissions. Also a bug has been fixed to run failing requests (status >= 400).

fix(pact-runner): Enabled multi-auth support in pact runner and fixed expected failure of request

---

doc/Screenshot Automation.md
src/c8yscrn/cypress/screenshots.cy.js
src/c8yscrn/runner-helper.spec.ts
src/c8yscrn/runner-helper.ts
src/c8yscrn/runner.ts
src/c8yscrn/schema.json
src/lib/pact/cypresspact.ts
src/lib/pact/cypresspreprocessor.ts
src/lib/pact/runner.ts
src/lib/screenshots/types.ts
src/shared/c8yctrl/httpcontroller.ts
src/shared/types.ts
src/shared/util.spec.ts
src/shared/util.ts
test/cypress.config.ts
test/cypress/e2e/screenshot-runner.cy.ts

Allow more flexible integration of `C8yScreenshotRunner` into Cypress projects. `C8yScreenshotRunner` now supports selecting the screenshot workflows to run via options argument and use within existing cypress tests.
```typescript
const runner = new C8yScreenshotRunner();
describe("Cockpit tests", () => {
beforeEach(() => {
// setup, configure interceptions, etc
});
// run with tags, image or titles filter 
runner.run({ tags: ["cockpit"] });
});
describe("DTM tests", () => {
beforeEach(() => {
// setup, configure interceptions, etc
});
runner.run({ titles: ["dtm", "assets", "import"] });
})
```

fix(c8yscrn): ScreenshotRunner creates tests as hierarchy

---

packages/pact-runner/cypress.config.ts
src/shared/c8ypact/adapter/fileadapter-js.spec.ts
src/shared/c8ypact/adapter/fileadapter.spec.ts
src/shared/c8ypact/adapter/fileadapter.ts
test/fixtures/js/cjstest.cjs
test/fixtures/js/jstest.js

`C8yPactDefaultFileAdapter` now supports `yaml` as well as `(c)js` loading of `C8yPact` files. Using Javascript is useful if you are using `C8yPact` files for API testing to dynamically create records and reduce duplication required in `json`. To enable Javascript, `C8yPactDefaultFileAdapter` requires the `enableJavaScript` config option to be enabled. By default, Javascript support is disabled.
```typescript
import { defineConfig } from 'cypress';
import { configureC8yPlugin } from 'cumulocity-cypress/plugin';
module.exports = defineConfig({
e2e: {
setupNodeEvents(on, config) {
const adapter = new C8yPactDefaultFileAdapter("/my/custom/pact/location", {
enableJavaScript: true,
});
configureC8yPlugin(on, config, {
pactAdapter: adapter,
});
return config;
},
},
});
```

feat(c8ypact): Allow loading yaml and js files using C8yPactDefaultFileAdapter

---

src/lib/commands/c8yclient.ts

When using `c8yclient` to query collection of objects as for example with
```typescript
cy.c8yclient((c) => c.application.listByUser()).then(({ body }) => {
console.log(body.applications);
});
```
the response collection is now correctly inferring the type of `body.applications` as with `applications?: IApplication[]`.

fix(c8yclient): Fixed c8yclient collection response type inference
